import "oaidl.idl";
import "ocidl.idl";

[
    uuid (49C68149-D4D0-41CA-A954-2FA8DE14ED31), // You must change this when you change the interface
    version(1.0),
]

interface Plugin
{
    int RpcStart([in] handle_t IDL_handle);
    int RpcShutdown([in] handle_t IDL_handle);
    boolean RpcPluginHealthCheck([in] handle_t IDL_handle);
    void RpcCommandPlugin([in] handle_t IDL_handle, [in] int command, [in, out, string] char* result);
}